image: uber/android-build-environment

pipelines:
  default:
    - step:
        size: 2x
        caches:
          - android-sdk
          - build-cache
          - gradle-wrapper
        script:
          - mkdir "${ANDROID_HOME}/licenses"
          - echo '24333f8a63b6825ea9c5514f83c2829b004d1fee' > ${ANDROID_HOME}/licenses/android-sdk-license
          - ./gradlew assembleDebug
definitions:
  caches:
    android-sdk: ${ANDROID_HOME}
    build-cache: ${HOME}/.android/build-cache
    gradle-wrapper: ~/.gradle/wrapper