package reach52.marketplace.community.models.medication

data class Medication(

        val dosage: String,
        val form: String,
        val id: String,
        val ingredients: List<String>,
        val name: String,
        val packageSize: Int,
        val price: Double,
        val supplier: String,
        val vat: Boolean
//        val barCode: Option<String>,
//        val dosages: List<Language>,
//        val descriptions: List<Language>,
//        val forms: List<Language>,
//        val handlingInstr: List<Language>,
//        val isoCountry: String,
//        val isoCurrency: String,
//        val id: String,
//        val information: List<Language>,
//        val ingredients: List<Language>,
//        val isVatExclusive: Boolean,
//        val medClass: Option<String>,
//        val medCode: Option<String>,
//        val manufacturer: Option<String>,
//        val names: List<Language>,
//        val packageSize: Int,
//        val prodCategories: Option<String>,
//        val price:Double,
//        val promotions: Option<String>,
//        val reqRx: Boolean,
//        val r52Code: String,
//        val r52CatNo: String,
//        val r52SupplierCode: String,
//        val suppCode: String,
//        val status: String,
//        val suppCatNo: String,
//        val suppliers: List<Language>,
//        val type: String,
//        val vatRate: Double,
//        val USDPrice: Option<Double>,
//        val createdBy: CreatedBy,
//        val updatedBy: List<CreatedBy>
)
